/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libreria;

import java.util.ArrayList;

/**
 *
 * @author alumnos
 */
public class frmLibreria extends javax.swing.JFrame {

    /**
     * Creates new form frmLibreria
     */
    public frmLibreria() {
        
        initComponents();
       
    }
     ArrayList<metodosLibreria> mLibro=new ArrayList<>();
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIsbn = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnLibrosxeditorial = new javax.swing.JButton();
        btnMostrarlibros = new javax.swing.JButton();
        btnValorlibros = new javax.swing.JButton();
        btnAgregarlibro = new javax.swing.JButton();
        cbxEditorial = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArlibreria = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnPoslibromayor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIsbn.setText("Isbn");

        lblValor.setText("Valor");

        lblEditorial.setText("Editorial");

        btnLibrosxeditorial.setText("Libros por Editorial");
        btnLibrosxeditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosxeditorialActionPerformed(evt);
            }
        });

        btnMostrarlibros.setText("Mostrar libros");
        btnMostrarlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarlibrosActionPerformed(evt);
            }
        });

        btnValorlibros.setText("Valor libros");
        btnValorlibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValorlibrosActionPerformed(evt);
            }
        });

        btnAgregarlibro.setText("Agregar libro");
        btnAgregarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarlibroActionPerformed(evt);
            }
        });

        cbxEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "001 Addison Wesley", "002  Mc Graw Hill", "003 Prentice Hall" }));

        txtArlibreria.setColumns(20);
        txtArlibreria.setRows(5);
        jScrollPane1.setViewportView(txtArlibreria);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pila-de-libros-aislados-en-fondo-blanco-estilo-dibujos-animados-ilustraciones-vectoriales-sobre-iconos-caricatura-188364726.jpg"))); // NOI18N

        btnPoslibromayor.setText("Posición libro con mayor valor");
        btnPoslibromayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoslibromayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnValorlibros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPoslibromayor)
                            .addComponent(btnMostrarlibros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLibrosxeditorial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIsbn)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditorial)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarlibro)))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbn)
                    .addComponent(lblValor)
                    .addComponent(lblEditorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarlibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLibrosxeditorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarlibros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnValorlibros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPoslibromayor))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarlibroActionPerformed
        // TODO add your handling code here:
         metodosLibreria libro=new metodosLibreria(txtIsbn.getText(),Float.parseFloat(txtValor.getText()),cbxEditorial.getSelectedItem().toString());
         mLibro.add(libro);
         txtArlibreria.setText("");   
    }//GEN-LAST:event_btnAgregarlibroActionPerformed

    private void btnMostrarlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarlibrosActionPerformed
        // TODO add your handling code here:
        txtArlibreria.append("N°\tLibro\tValor\tEditorial\n");
        if (evt.getSource() == btnMostrarlibros) {
            for (int i = 0; i < mLibro.size(); i++) {
                txtArlibreria.append((i + 1) + "\t" + mLibro.get(i).getIsbn() + "\t" + mLibro.get(i).getValor() + "\t" + mLibro.get(i).getEditorial() + "\n");
            }
        }
    }//GEN-LAST:event_btnMostrarlibrosActionPerformed

    private void btnLibrosxeditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosxeditorialActionPerformed
        // TODO add your handling code here:
        txtArlibreria.setText(""); 
        String e1 = "001 Addison Wesley";
        String e2 = "002  Mc Graw Hill";
        String e3 = "003 Prentice Hall";
        String liEdi1[] = new String[mLibro.size()];
        int conLi1 = 0;
        int conLi2 = 0;
        int conLi3 = 0;
        txtArlibreria.setText("");
        txtArlibreria.append("Editorial 001 Addison Wesley\n");
        for (int i = 0; i < mLibro.size(); i++) {
            if (mLibro.get(i).getEditorial() == e1) {
                liEdi1[i] = mLibro.get(i).getIsbn();
                conLi1++;
                txtArlibreria.append(liEdi1[i] + "\n");
            }
        }
        txtArlibreria.append("Editorial 002 Mc Graw Hill\n");
        for (int i = 0; i < mLibro.size(); i++) {
            if (mLibro.get(i).getEditorial() == e2) {
                liEdi1[i] = mLibro.get(i).getIsbn();
                conLi2++;
                txtArlibreria.append(liEdi1[i] + "\n");
            }
        }
        txtArlibreria.append("Editorial 003Prentice Hall\n");
        for (int i = 0; i < mLibro.size(); i++) {
            if (mLibro.get(i).getEditorial() == e3) {
                liEdi1[i] = mLibro.get(i).getIsbn();
                conLi3++;
                txtArlibreria.append(liEdi1[i] + "\n");
            }
        }
    }//GEN-LAST:event_btnLibrosxeditorialActionPerformed

    private void btnValorlibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValorlibrosActionPerformed
        // TODO add your handling code here:
        txtArlibreria.setText(""); 
        float totalLibros = 0;
         txtArlibreria.append("Libros en la biblioteca\n");
        for (int i = 0; i < mLibro.size(); i++) {
                totalLibros +=mLibro.get(i).getValor();
                txtArlibreria.append((i + 1) + "\t" + mLibro.get(i).getIsbn() + "\t" + mLibro.get(i).getValor() + "\t" + mLibro.get(i).getEditorial() + "\n");
        }
         txtArlibreria.append("Valor total de los libros en la biblioteca: " +totalLibros);  
    }//GEN-LAST:event_btnValorlibrosActionPerformed

    public int mayorPosicion(){
        int posM=0;
        float valM = 0;
        for (int i = 0; i < mLibro.size(); i++) {
             if (mLibro.get(i).getValor() > valM) {
                 valM =mLibro.get(i).getValor();
            }
        }  
        for (int i = 0; i < mLibro.size(); i++) {
            if (mLibro.get(i).getValor() == valM) {
                posM++;
            }
        }
        return posM;
    }
    private void btnPoslibromayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoslibromayorActionPerformed
        // TODO add your handling code here:
        txtArlibreria.setText(""); 
        txtArlibreria.append("Libros en la biblioteca\n");
        for (int i = 0; i < mLibro.size(); i++) {
            txtArlibreria.append((i + 1) + "\t" + mLibro.get(i).getIsbn() + "\t" + mLibro.get(i).getValor() + "\t" + mLibro.get(i).getEditorial() + "\n");
        }
        txtArlibreria.append("La posicion del libro con mayor valor es:" + mayorPosicion());
        txtArlibreria.append("\nEl libro es : " + mLibro.get(mayorPosicion()-1).getIsbn()+ " y su precio es: " + mLibro.get(mayorPosicion()-1).getValor());
    }//GEN-LAST:event_btnPoslibromayorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLibreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarlibro;
    private javax.swing.JButton btnLibrosxeditorial;
    private javax.swing.JButton btnMostrarlibros;
    private javax.swing.JButton btnPoslibromayor;
    private javax.swing.JButton btnValorlibros;
    private javax.swing.JComboBox<String> cbxEditorial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextArea txtArlibreria;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
